import type { WorkspaceSnapshot } from '../matrix/viewModels';

const now = Date.now();
const minutesAgo = (minutes: number): number => now - minutes * 60_000;

export const demoWorkspace: WorkspaceSnapshot = {
  mode: 'demo',
  connection: 'online',
  user: {
    id: '@you:example.com',
    displayName: 'Spencer',
    presence: 'online',
    statusMessage: 'Building a better buddy list ✨',
  },
  spaces: [
    {
      id: 'home',
      name: 'Home',
      initials: 'A',
      color: '#267ec1',
      kind: 'home',
      membership: 'join',
      canManage: false,
      childIds: ['welcome', 'mara', 'pixel', 'dev-shack', 'gif-club', 'late-night'],
      directRoomIds: ['welcome', 'mara', 'pixel', 'dev-shack', 'gif-club', 'late-night'],
      childSpaceIds: ['friends', 'lab', 'music'],
      parentSpaceIds: [],
      roomIds: ['welcome', 'mara', 'pixel', 'dev-shack', 'gif-club', 'late-night'],
      unreadCount: 4,
      highlighted: true,
    },
    {
      id: 'directs',
      name: 'Direct Messages',
      initials: 'DM',
      color: '#607fa0',
      kind: 'directs',
      membership: 'join',
      canManage: false,
      childIds: ['mara', 'pixel'],
      directRoomIds: ['mara', 'pixel'],
      childSpaceIds: [],
      parentSpaceIds: [],
      roomIds: ['mara', 'pixel'],
      unreadCount: 1,
      highlighted: false,
    },
    {
      id: 'friends',
      name: 'Friends',
      initials: 'FR',
      color: '#a25fb2',
      kind: 'matrix',
      membership: 'join',
      canManage: true,
      ownPowerLevel: 100,
      background: { preset: 'blue-lagoon' },
      backgroundPolicy: {
        mode: 'decorators',
        requiredPowerLevel: 25,
        canChange: true,
        canManage: true,
      },
      childIds: ['mara', 'pixel', 'vidja-gamez'],
      directRoomIds: ['mara', 'pixel'],
      childSpaceIds: ['vidja-gamez'],
      parentSpaceIds: [],
      roomIds: ['mara', 'pixel', 'welcome', 'gif-club', 'dev-shack'],
      unreadCount: 4,
      highlighted: true,
    },
    {
      id: 'vidja-gamez',
      name: 'Vidja Gamez',
      initials: 'VG',
      color: '#586fbd',
      kind: 'matrix',
      membership: 'join',
      canManage: true,
      childIds: ['welcome', 'gif-club', 'dev-shack'],
      directRoomIds: ['welcome', 'gif-club', 'dev-shack'],
      childSpaceIds: [],
      parentSpaceIds: ['friends'],
      roomIds: ['welcome', 'gif-club', 'dev-shack'],
      unreadCount: 3,
      highlighted: true,
    },
    {
      id: 'lab',
      name: 'Homelab',
      initials: 'HL',
      color: '#39946e',
      kind: 'matrix',
      membership: 'join',
      canManage: true,
      childIds: ['dev-shack'],
      directRoomIds: ['dev-shack'],
      childSpaceIds: [],
      parentSpaceIds: [],
      roomIds: ['dev-shack'],
      unreadCount: 0,
      highlighted: false,
    },
    {
      id: 'music',
      name: 'Music',
      initials: '♫',
      color: '#d56b72',
      kind: 'matrix',
      membership: 'join',
      canManage: true,
      childIds: ['late-night'],
      directRoomIds: ['late-night'],
      childSpaceIds: [],
      parentSpaceIds: [],
      roomIds: ['late-night'],
      unreadCount: 0,
      highlighted: false,
    },
  ],
  spaceRoomPreviews: {},
  rooms: [
    {
      id: 'welcome',
      name: 'Welcome Lounge',
      kind: 'room',
      group: 'Favorites',
      membership: 'join',
      lastMessage: 'The buddy list is back.',
      unreadCount: 3,
      timelineUnreadCount: 3,
      readUpToMessageId: 'm2',
      highlighted: true,
      encrypted: true,
      canManage: true,
      ownPowerLevel: 100,
      background: { preset: 'aero-sky' },
      backgroundPolicy: {
        mode: 'decorators',
        requiredPowerLevel: 25,
        canChange: true,
        canManage: true,
      },
      updatedAt: minutesAgo(1),
    },
    {
      id: 'mara',
      name: 'Mara Chen',
      kind: 'direct',
      group: 'Direct Messages',
      membership: 'join',
      presence: 'online',
      statusMessage: 'listening to The Postal Service',
      lastMessage: 'That graphite theme is perfect.',
      unreadCount: 1,
      timelineUnreadCount: 1,
      readUpToMessageId: 'mara-1',
      highlighted: false,
      encrypted: true,
      background: { preset: 'green-meadow' },
      backgroundPolicy: {
        mode: 'members',
        requiredPowerLevel: 0,
        canChange: true,
        canManage: false,
      },
      updatedAt: minutesAgo(4),
    },
    {
      id: 'pixel',
      name: 'PixelGhost',
      kind: 'direct',
      group: 'Direct Messages',
      membership: 'join',
      presence: 'away',
      statusMessage: 'brb — burning a mix CD',
      lastMessage: 'brb — burning a mix CD',
      unreadCount: 0,
      highlighted: false,
      encrypted: true,
      updatedAt: minutesAgo(27),
    },
    {
      id: 'dev-shack',
      name: 'Dev Shack',
      kind: 'room',
      group: 'Rooms',
      membership: 'join',
      lastMessage: 'CI is green again!',
      unreadCount: 0,
      highlighted: false,
      encrypted: true,
      updatedAt: minutesAgo(11),
    },
    {
      id: 'gif-club',
      name: 'GIF Club',
      kind: 'room',
      group: 'Rooms',
      membership: 'join',
      lastMessage: 'Animated responsibly.',
      unreadCount: 0,
      highlighted: false,
      encrypted: false,
      updatedAt: minutesAgo(63),
    },
    {
      id: 'late-night',
      name: 'Late Night Radio',
      kind: 'room',
      group: 'Rooms',
      membership: 'join',
      lastMessage: 'Now playing: Such Great Heights',
      unreadCount: 0,
      highlighted: false,
      encrypted: true,
      updatedAt: minutesAgo(91),
    },
  ],
  messagesByRoom: {
    welcome: [
      {
        id: 'm1',
        roomId: 'welcome',
        senderId: '@mara:example.com',
        senderName: 'Mara',
        body: "Okay, this already feels like the chat app we should've had all along.",
        timestamp: minutesAgo(34),
        kind: 'text',
        isOwn: false,
      },
      {
        id: 'm2',
        roomId: 'welcome',
        senderId: '@you:example.com',
        senderName: 'Spencer',
        body: 'The goal: 2006 in spirit, 2026 where it matters.',
        timestamp: minutesAgo(31),
        kind: 'text',
        isOwn: true,
        reactions: [{ key: '💙', count: 3, reacted: true }],
        readBy: [{ id: '@mara:example.com', displayName: 'Mara' }],
      },
      {
        id: 'm3',
        roomId: 'welcome',
        senderId: '@pixel:example.com',
        senderName: 'PixelGhost',
        body: 'carefully polishes every glossy button',
        timestamp: minutesAgo(19),
        kind: 'emote',
        isOwn: false,
        readBy: [{ id: '@aimie:example.com', displayName: 'Aimie' }],
      },
      {
        id: 'm4',
        roomId: 'welcome',
        senderId: '@aimie:example.com',
        senderName: 'Aimie',
        body: 'Encryption is on. Nostalgia does not require compromising your messages.',
        timestamp: minutesAgo(8),
        kind: 'notice',
        isOwn: false,
      },
      {
        id: 'm5',
        roomId: 'welcome',
        senderId: '@mara:example.com',
        senderName: 'Mara',
        body: 'The buddy list is back. Nature is healing.',
        timestamp: minutesAgo(1),
        kind: 'text',
        isOwn: false,
        reactions: [
          { key: '✨', count: 4, reacted: false },
          { key: '🫧', count: 2, reacted: false },
        ],
        readBy: [{ id: '@pixel:example.com', displayName: 'PixelGhost' }],
      },
    ],
    mara: [
      {
        id: 'mara-1',
        roomId: 'mara',
        senderId: '@mara:example.com',
        senderName: 'Mara',
        body: 'That graphite theme is perfect.',
        timestamp: minutesAgo(4),
        kind: 'text',
        isOwn: false,
      },
      {
        id: 'mara-2',
        roomId: 'mara',
        senderId: '@you:example.com',
        senderName: 'Spencer',
        body: 'Wait until you see the meadow backdrop.',
        timestamp: minutesAgo(2),
        kind: 'text',
        isOwn: true,
        readBy: [{ id: '@mara:example.com', displayName: 'Mara' }],
      },
    ],
    pixel: [],
    'dev-shack': [],
    'gif-club': [],
    'late-night': [],
  },
  membersByRoom: {
    welcome: [
      { id: '@you:example.com', displayName: 'Spencer', presence: 'online', role: 'Admin', powerLevel: 100 },
      { id: '@mara:example.com', displayName: 'Mara', presence: 'online', powerLevel: 0 },
      { id: '@aimie:example.com', displayName: 'Aimie', presence: 'online', powerLevel: 0 },
      { id: '@pixel:example.com', displayName: 'PixelGhost', presence: 'away', role: 'Decorator', powerLevel: 25 },
    ],
    mara: [{ id: '@mara:example.com', displayName: 'Mara', presence: 'online' }],
    pixel: [{ id: '@pixel:example.com', displayName: 'PixelGhost', presence: 'away' }],
    'dev-shack': [],
    'gif-club': [],
    'late-night': [],
    friends: [
      { id: '@you:example.com', displayName: 'Spencer', presence: 'online', role: 'Admin', powerLevel: 100 },
      { id: '@mara:example.com', displayName: 'Mara', presence: 'online', powerLevel: 0 },
      { id: '@pixel:example.com', displayName: 'PixelGhost', presence: 'away', role: 'Decorator', powerLevel: 25 },
    ],
  },
};
