import type { WorkspaceSnapshot } from '../matrix/viewModels';

const now = Date.now();
const minutesAgo = (minutes: number): number => now - minutes * 60_000;

export const demoWorkspace: WorkspaceSnapshot = {
  mode: 'demo',
  connection: 'online',
  user: {
    id: '@you:example.com',
    displayName: 'Spencer',
    presence: 'online',
    statusMessage: 'Building a better buddy list ✨',
  },
  spaces: [
    {
      id: 'home',
      name: 'Home',
      initials: 'A',
      color: '#267ec1',
      roomIds: ['welcome', 'mara', 'pixel', 'dev-shack', 'gif-club', 'late-night'],
    },
    {
      id: 'friends',
      name: 'Friends',
      initials: 'FR',
      color: '#a25fb2',
      roomIds: ['welcome', 'mara', 'pixel'],
    },
    {
      id: 'lab',
      name: 'Homelab',
      initials: 'HL',
      color: '#39946e',
      roomIds: ['dev-shack'],
    },
    {
      id: 'music',
      name: 'Music',
      initials: '♫',
      color: '#d56b72',
      roomIds: ['late-night'],
    },
  ],
  rooms: [
    {
      id: 'welcome',
      name: 'Welcome Lounge',
      kind: 'room',
      group: 'Favorites',
      membership: 'join',
      lastMessage: 'The buddy list is back.',
      unreadCount: 3,
      highlighted: true,
      encrypted: true,
      updatedAt: minutesAgo(1),
    },
    {
      id: 'mara',
      name: 'Mara Chen',
      kind: 'direct',
      group: 'Direct Messages',
      membership: 'join',
      presence: 'online',
      statusMessage: 'listening to The Postal Service',
      lastMessage: 'That graphite theme is perfect.',
      unreadCount: 1,
      highlighted: false,
      encrypted: true,
      updatedAt: minutesAgo(4),
    },
    {
      id: 'pixel',
      name: 'PixelGhost',
      kind: 'direct',
      group: 'Direct Messages',
      membership: 'join',
      presence: 'away',
      statusMessage: 'brb — burning a mix CD',
      lastMessage: 'brb — burning a mix CD',
      unreadCount: 0,
      highlighted: false,
      encrypted: true,
      updatedAt: minutesAgo(27),
    },
    {
      id: 'dev-shack',
      name: 'Dev Shack',
      kind: 'room',
      group: 'Rooms',
      membership: 'join',
      lastMessage: 'CI is green again!',
      unreadCount: 0,
      highlighted: false,
      encrypted: true,
      updatedAt: minutesAgo(11),
    },
    {
      id: 'gif-club',
      name: 'GIF Club',
      kind: 'room',
      group: 'Rooms',
      membership: 'join',
      lastMessage: 'Animated responsibly.',
      unreadCount: 0,
      highlighted: false,
      encrypted: false,
      updatedAt: minutesAgo(63),
    },
    {
      id: 'late-night',
      name: 'Late Night Radio',
      kind: 'room',
      group: 'Rooms',
      membership: 'join',
      lastMessage: 'Now playing: Such Great Heights',
      unreadCount: 0,
      highlighted: false,
      encrypted: true,
      updatedAt: minutesAgo(91),
    },
  ],
  messagesByRoom: {
    welcome: [
      {
        id: 'm1',
        roomId: 'welcome',
        senderId: '@mara:example.com',
        senderName: 'Mara',
        body: "Okay, this already feels like the chat app we should've had all along.",
        timestamp: minutesAgo(34),
        kind: 'text',
        isOwn: false,
      },
      {
        id: 'm2',
        roomId: 'welcome',
        senderId: '@you:example.com',
        senderName: 'Spencer',
        body: 'The goal: 2006 in spirit, 2026 where it matters.',
        timestamp: minutesAgo(31),
        kind: 'text',
        isOwn: true,
        reactions: [{ key: '💙', count: 3, reacted: true }],
      },
      {
        id: 'm3',
        roomId: 'welcome',
        senderId: '@pixel:example.com',
        senderName: 'PixelGhost',
        body: 'carefully polishes every glossy button',
        timestamp: minutesAgo(19),
        kind: 'emote',
        isOwn: false,
      },
      {
        id: 'm4',
        roomId: 'welcome',
        senderId: '@aimie:example.com',
        senderName: 'Aimie',
        body: 'Encryption is on. Nostalgia does not require compromising your messages.',
        timestamp: minutesAgo(8),
        kind: 'notice',
        isOwn: false,
      },
      {
        id: 'm5',
        roomId: 'welcome',
        senderId: '@mara:example.com',
        senderName: 'Mara',
        body: 'The buddy list is back. Nature is healing.',
        timestamp: minutesAgo(1),
        kind: 'text',
        isOwn: false,
        reactions: [
          { key: '✨', count: 4, reacted: false },
          { key: '🫧', count: 2, reacted: false },
        ],
      },
    ],
    mara: [
      {
        id: 'mara-1',
        roomId: 'mara',
        senderId: '@mara:example.com',
        senderName: 'Mara',
        body: 'That graphite theme is perfect.',
        timestamp: minutesAgo(4),
        kind: 'text',
        isOwn: false,
      },
    ],
    pixel: [],
    'dev-shack': [],
    'gif-club': [],
    'late-night': [],
  },
  membersByRoom: {
    welcome: [
      { id: '@you:example.com', displayName: 'Spencer', presence: 'online', role: 'Admin' },
      { id: '@mara:example.com', displayName: 'Mara', presence: 'online' },
      { id: '@aimie:example.com', displayName: 'Aimie', presence: 'online' },
      { id: '@pixel:example.com', displayName: 'PixelGhost', presence: 'away' },
    ],
    mara: [{ id: '@mara:example.com', displayName: 'Mara', presence: 'online' }],
    pixel: [{ id: '@pixel:example.com', displayName: 'PixelGhost', presence: 'away' }],
    'dev-shack': [],
    'gif-club': [],
    'late-night': [],
  },
};
